// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVK2g9VLu7wqoEvkLLc7C9u5e0nfEGkO0',
    appId: '1:405588508530:web:7cdd24798fb6a9eb2327eb',
    messagingSenderId: '405588508530',
    projectId: 'test-flutter-flow1-bnxb4q',
    authDomain: 'test-flutter-flow1-bnxb4q.firebaseapp.com',
    storageBucket: 'test-flutter-flow1-bnxb4q.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-qsrFGpDAjouOqUA7yb4Rq1a7oCE3kDA',
    appId: '1:405588508530:android:ef6a9c40bb1280c42327eb',
    messagingSenderId: '405588508530',
    projectId: 'test-flutter-flow1-bnxb4q',
    storageBucket: 'test-flutter-flow1-bnxb4q.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiX-Jz_un5kGXcAyHFI2I9zV3IAOCFdts',
    appId: '1:405588508530:ios:1598dd3f5624ba952327eb',
    messagingSenderId: '405588508530',
    projectId: 'test-flutter-flow1-bnxb4q',
    storageBucket: 'test-flutter-flow1-bnxb4q.appspot.com',
    androidClientId: '405588508530-c7ul3urda9gkam5q0inul289n0n4jjbd.apps.googleusercontent.com',
    iosClientId: '405588508530-6ud14s4gqgo7rqh6la8bmd8u9731s26p.apps.googleusercontent.com',
    iosBundleId: 'com.example.haruMatch2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiX-Jz_un5kGXcAyHFI2I9zV3IAOCFdts',
    appId: '1:405588508530:ios:1b804b4f42e6dbc12327eb',
    messagingSenderId: '405588508530',
    projectId: 'test-flutter-flow1-bnxb4q',
    storageBucket: 'test-flutter-flow1-bnxb4q.appspot.com',
    androidClientId: '405588508530-c7ul3urda9gkam5q0inul289n0n4jjbd.apps.googleusercontent.com',
    iosClientId: '405588508530-unsemgcec3sa7q84ti5v0m7rd728bsji.apps.googleusercontent.com',
    iosBundleId: 'com.example.haruMatch2.RunnerTests',
  );
}
